export async function handler(event) {
  const data = {
    hentai3dvanguoi: [
      "https://files.catbox.moe/vysf40.mp4",
      "https://files.catbox.moe/1py1jv.mp4",
      "https://files.catbox.moe/tfeuzt.mp4",
      "https://files.catbox.moe/uu49i9.mp4",
      "https://files.catbox.moe/n1rv9x.mp4",
      "https://files.catbox.moe/n16b22.mp4",
      "https://files.catbox.moe/7stgrz.mp4",
      "https://files.catbox.moe/p59oyz.mp4",
      "https://files.catbox.moe/9sbhov.mp4",
      "https://files.catbox.moe/0tijln.mp4",
      "https://files.catbox.moe/fhj82c.mp4",
      "https://files.catbox.moe/440xpk.mp4",
      "https://files.catbox.moe/b1a5yt.mp4",
      "https://files.catbox.moe/7zbnhc.mp4",
      "https://files.catbox.moe/oza3qo.mp4",
      "https://files.catbox.moe/9t0i7k.mp4",
      "https://files.catbox.moe/ebb21n.mp4",
      "https://files.catbox.moe/ddkjnh.mp4",
      "https://files.catbox.moe/rlsc5e.mp4",
      "https://files.catbox.moe/t61f69.mp4",
      "https://files.catbox.moe/2kysgb.mp4",
      "https://files.catbox.moe/upaf0f.mp4",
      "https://files.catbox.moe/7970lm.mp4",
      "https://files.catbox.moe/vnrket.mp4",
      "https://files.catbox.moe/nv2zfa.mp4",
      "https://files.catbox.moe/tapgiw.mp4",
      "https://files.catbox.moe/640bn2.mp4",
      "https://files.catbox.moe/doc4cb.mp4",
      "https://files.catbox.moe/cbhjkt.mp4",
      "https://files.catbox.moe/owb583.mp4",
      "https://files.catbox.moe/30hkmk.mp4",
      "https://files.catbox.moe/kci6zp.mp4",
      "https://files.catbox.moe/0xo8k3.mp4",
      "https://files.catbox.moe/ayc6wh.mp4",
      "https://files.catbox.moe/6jutt8.mp4",
      "https://files.catbox.moe/sxwu2y.mp4",
      "https://files.catbox.moe/x47mtv.mp4"
    ],
    hentai2d: [
      "https://files.catbox.moe/z7e55g.mp4",
      "https://files.catbox.moe/sblrwx.mp4",
      "https://files.catbox.moe/gazxjl.mp4",
      "https://files.catbox.moe/keyadc.mp4",
      "https://files.catbox.moe/zxip8v.mp4",
      "https://files.catbox.moe/vp46yt.mp4",
      "https://files.catbox.moe/2cedfl.mp4",
      "https://files.catbox.moe/mvnobl.mp4",
      "https://files.catbox.moe/4s3zs4.mp4",
      "https://files.catbox.moe/4q77i2.mp4",
      "https://files.catbox.moe/68h04n.mp4",
      "https://files.catbox.moe/ig0tfb.mp4",
      "https://files.catbox.moe/g28l7w.mp4",
      "https://files.catbox.moe/mz326w.mp4",
      "https://files.catbox.moe/yv8blm.mp4",
      "https://files.catbox.moe/m1h36r.mp4",
      "https://files.catbox.moe/ygokgk.mp4",
      "https://files.catbox.moe/mg1fyj.mp4",
      "https://files.catbox.moe/gyrugm.mp4",
      "https://files.catbox.moe/m7htss.mp4",
      "https://files.catbox.moe/i2nscc.mp4",
      "https://files.catbox.moe/m0u1on.mp4",
      "https://files.catbox.moe/q1q2fr.mp4",
      "https://files.catbox.moe/bgn1gx.mp4",
      "https://files.catbox.moe/h4zo6x.mp4",
      "https://files.catbox.moe/a3q8ql.mp4",
      "https://files.catbox.moe/93fco3.mp4",
      "https://files.catbox.moe/ovdaq3.mp4",
      "https://files.catbox.moe/7dg1xd.mp4",
      "https://files.catbox.moe/xu78ci.mp4",
      "https://files.catbox.moe/q4u2mh.mp4",
      "https://files.catbox.moe/j43q6s.mp4",
      "https://files.catbox.moe/ercjty.mp4",
      "https://files.catbox.moe/52pn55.mp4",
      "https://files.catbox.moe/p19l4n.mp4",
      "https://files.catbox.moe/dle065.mp4",
      "https://files.catbox.moe/2nkkjq.mp4",
      "https://files.catbox.moe/sb4pee.mp4",
      "https://files.catbox.moe/3v0ye9.mp4",
      "https://files.catbox.moe/ablokb.mp4",
      "https://files.catbox.moe/iqz6yb.mp4",
      "https://files.catbox.moe/jr8pnp.mp4",
      "https://files.catbox.moe/x6snpw.mp4",
      "https://files.catbox.moe/u4mjwz.mp4",
      "https://files.catbox.moe/k2tpey.mp4",
      "https://files.catbox.moe/yi663h.mp4",
      "https://files.catbox.moe/lxttw3.mp4",
      "https://files.catbox.moe/p0xf94.mp4",
      "https://files.catbox.moe/611p8t.mp4",
      "https://files.catbox.moe/xreac8.mp4",
      "https://files.catbox.moe/9wgv37.mp4",
      "https://files.catbox.moe/2uqhar.mp4",
      "https://files.catbox.moe/c7cj9l.mp4",
      "https://files.catbox.moe/5zhwzw.mp4",
      "https://files.catbox.moe/2qbbhe.mp4",
      "https://files.catbox.moe/j7a6dv.mp4",
      "https://files.catbox.moe/6ml9du.mp4",
      "https://files.catbox.moe/xa9oaf.mp4",
      "https://files.catbox.moe/89kjz4.mp4",
      "https://files.catbox.moe/rnd3h2.mp4",
      "https://files.catbox.moe/1hc7ti.mp4",
      "https://files.catbox.moe/mnxye8.mp4",
      "https://files.catbox.moe/zrva9c.mp4",
      "https://files.catbox.moe/zbvplt.mp4",
      "https://files.catbox.moe/g2gn9i.mp4",
      "https://files.catbox.moe/3s56b7.mp4",
      "https://files.catbox.moe/3r0p8a.mp4",
      "https://files.catbox.moe/mhqmj6.mp4",
      "https://files.catbox.moe/ppivcx.mp4",
      "https://files.catbox.moe/ppx804.mp4",
      "https://files.catbox.moe/8y8aoi.mp4",
      "https://files.catbox.moe/ligbln.mp4",
      "https://files.catbox.moe/00xgff.mp4",
      "https://files.catbox.moe/ehucnx.mp4",
      "https://files.catbox.moe/20mqg6.mp4",
      "https://files.catbox.moe/kbtki0.mp4",
      "https://files.catbox.moe/8y27cv.mp4",
      "https://files.catbox.moe/dia20h.mp4",
      "https://files.catbox.moe/bfqpyz.mp4",
      "https://files.catbox.moe/89ksfw.mp4",
      "https://files.catbox.moe/cvrdii.mp4",
      "https://files.catbox.moe/yqhgv1.mp4",
      "https://files.catbox.moe/wj3n0y.mp4",
      "https://files.catbox.moe/lm23it.mp4",
      "https://files.catbox.moe/1yq8pa.mp4",
      "https://files.catbox.moe/1lw5uq.mp4",
      "https://files.catbox.moe/wxrzmu.mp4",
      "https://files.catbox.moe/twsx3b.mp4",
      "https://files.catbox.moe/olnjbf.mp4",
      "https://files.catbox.moe/juepps.mp4",
      "https://files.catbox.moe/wm82rw.mp4",
      "https://files.catbox.moe/9duui7.mp4",
      "https://files.catbox.moe/3k9lne.mp4",
      "https://files.catbox.moe/l81whr.mp4",
      "https://files.catbox.moe/1649a0.mp4",
      "https://files.catbox.moe/f2xkdk.mp4",
      "https://files.catbox.moe/3uqgv3.mp4",
      "https://files.catbox.moe/qlxomg.mp4",
      "https://files.catbox.moe/xsvcu2.mp4",
      "https://files.catbox.moe/ps5sa2.mp4",
      "https://files.catbox.moe/yg58ow.mp4",
      "https://files.catbox.moe/vuu107.mp4",
      "https://files.catbox.moe/4cdxo5.mp4",
      "https://files.catbox.moe/6ntfsh.mp4",
      "https://files.catbox.moe/72c29i.mp4",
      "https://files.catbox.moe/8grn1g.mp4",
      "https://files.catbox.moe/nehi8g.mp4",
      "https://files.catbox.moe/ajzjof.mp4",
      "https://files.catbox.moe/z7z8yl.mp4",
      "https://files.catbox.moe/k8ahka.mp4",
      "https://files.catbox.moe/2jijfi.mp4",
      "https://files.catbox.moe/clai8k.mp4",
      "https://files.catbox.moe/9zg2os.mp4",
      "https://files.catbox.moe/2ubobm.mp4",
      "https://files.catbox.moe/aak9xu.mp4",
      "https://files.catbox.moe/dj4a7z.mp4",
      "https://files.catbox.moe/fpbeyo.mp4",
      "https://files.catbox.moe/8r27rw.mp4",
      "https://files.catbox.moe/usszpf.mp4",
      "https://files.catbox.moe/04w54j.mp4",
      "https://files.catbox.moe/9j8r5b.mp4",
      "https://files.catbox.moe/q77mn8.mp4",
      "https://files.catbox.moe/20vkh0.mp4",
      "https://files.catbox.moe/ae50ob.mp4",
      "https://files.catbox.moe/7tt9d2.mp4",
      "https://files.catbox.moe/sx3jb1.mp4",
      "https://files.catbox.moe/g2q5lu.mp4",
      "https://files.catbox.moe/xhenhu.mp4",
      "https://files.catbox.moe/93t7ng.mp4",
      "https://files.catbox.moe/o4wxpw.mp4",
      "https://files.catbox.moe/gdpjmk.mp4",
      "https://files.catbox.moe/8ghuz8.mp4",
      "https://files.catbox.moe/6vi78s.mp4",
      "https://files.catbox.moe/9fesi2.mp4",
      "https://files.catbox.moe/a9rnni.mp4",
      "https://files.catbox.moe/805ib4.mp4",
      "https://files.catbox.moe/ankedd.mp4",
      "https://files.catbox.moe/it04br.mp4",
      "https://files.catbox.moe/we3ia1.mp4",
      "https://files.catbox.moe/uhmvew.mp4",
      "https://files.catbox.moe/7o56bt.mp4",
      "https://files.catbox.moe/quop1s.mp4",
      "https://files.catbox.moe/dkmi8o.mp4",
      "https://files.catbox.moe/pj4o3u.mp4",
      "https://files.catbox.moe/w4jlwv.mp4",
      "https://files.catbox.moe/15qgrq.mp4",
      "https://files.catbox.moe/zg97xq.mp4",
      "https://files.catbox.moe/zg97xq.mp4",
      "https://files.catbox.moe/ahfnlo.mp4",
      "https://files.catbox.moe/e8ofku.mp4",
      "https://files.catbox.moe/wkhavl.mp4",
      "https://files.catbox.moe/zzfged.mp4",
      "https://files.catbox.moe/k3ks6h.mp4",
      "https://files.catbox.moe/xpvkvj.mp4",
      "https://files.catbox.moe/xdsxe2.mp4",
      "https://files.catbox.moe/kw3mhx.mp4",
      "https://files.catbox.moe/hmxqpu.mp4",
      "https://files.catbox.moe/5s7iax.mp4",
      "https://files.catbox.moe/6hszmi.mp4",
      "https://files.catbox.moe/6arlcj.mp4",
      "https://files.catbox.moe/m2fuld.mp4",
      "https://files.catbox.moe/idt341.mp4",
      "https://files.catbox.moe/uwxl5l.mp4",
      "https://files.catbox.moe/tpc7ts.mp4",
      "https://files.catbox.moe/uchadk.mp4",
      "https://files.catbox.moe/pvgk5s.mp4",
      "https://files.catbox.moe/w2s3eb.mp4",
      "https://files.catbox.moe/z9xqyu.mp4",
      "https://files.catbox.moe/fiyskn.mp4",
      "https://files.catbox.moe/mjcopa.mp4",
      "https://files.catbox.moe/caggrm.mp4",
      "https://files.catbox.moe/7gl54i.mp4",
      "https://files.catbox.moe/gj8j3t.mp4",
      "https://files.catbox.moe/igjx8g.mp4",
      "https://files.catbox.moe/l737s1.mp4",
      "https://files.catbox.moe/4cbdkq.mp4",
      "https://files.catbox.moe/yxc4dp.mp4",
      "https://files.catbox.moe/207uvz.mp4",
      "https://files.catbox.moe/ve7jwn.mp4",
      "https://files.catbox.moe/phhajs.mp4",
      "https://files.catbox.moe/67a1vp.mp4",
      "https://files.catbox.moe/gwoowm.mp4",
      "https://files.catbox.moe/ncot8h.mp4",
      "https://files.catbox.moe/kqajm2.mp4",
      "https://files.catbox.moe/f18hsq.mp4",
      "https://files.catbox.moe/qcdg8n.mp4",
      "https://files.catbox.moe/ghdwge.mp4",
      "https://files.catbox.moe/lblp34.mp4",
      "https://files.catbox.moe/p4fqdv.mp4",
      "https://files.catbox.moe/1d62tk.mp4",
      "https://files.catbox.moe/hocgil.mp4",
      "https://files.catbox.moe/rongun.mp4",
      "https://files.catbox.moe/qx4gu0.mp4",
      "https://files.catbox.moe/kpffsx.mp4",
      "https://files.catbox.moe/h4sfhe.mp4",
      "https://files.catbox.moe/t3xs1t.mp4",
      "https://files.catbox.moe/r5jdev.mp4",
      "https://files.catbox.moe/hztla9.mp4",
      "https://files.catbox.moe/mthcxs.mp4",
      "https://files.catbox.moe/ovef9h.mp4",
      "https://files.catbox.moe/v2c2ye.mp4",
      "https://files.catbox.moe/r5k9xq.mp4",
      "https://files.catbox.moe/5rf9s2.mp4",
      "https://files.catbox.moe/1wzej8.mp4",
      "https://files.catbox.moe/zal1s0.mp4",
      "https://files.catbox.moe/o6xmkm.mp4",
      "https://files.catbox.moe/nqvpro.mp4",
      "https://files.catbox.moe/wnj1lw.mp4",
      "https://files.catbox.moe/4y0om5.mp4",
      "https://files.catbox.moe/u21m7x.mp4",
      "https://files.catbox.moe/jau93b.mp4",
      "https://files.catbox.moe/0ntnay.mp4",
      "https://files.catbox.moe/yqzxi7.mp4",
      "https://files.catbox.moe/ese3nq.mp4",
      "https://files.catbox.moe/d3v2lg.mp4",
      "https://files.catbox.moe/16q70n.mp4",
      "https://files.catbox.moe/cfj5ci.mp4",
      "https://files.catbox.moe/e6gcqm.mp4",
      "https://files.catbox.moe/c2iloh.mp4",
      "https://files.catbox.moe/26amkz.mp4",
      "https://files.catbox.moe/iqw6kd.mp4",
      "https://files.catbox.moe/82g886.mp4",
      "https://files.catbox.moe/tpkl13.mp4",
      "https://files.catbox.moe/p407uv.mp4",
      "https://files.catbox.moe/vd6v9y.mp4",
      "https://files.catbox.moe/669d8c.mp4",
      "https://files.catbox.moe/zoiwtk.mp4",
      "https://files.catbox.moe/3cdcen.mp4"
    ],
    hentai3d: [
      "https://files.catbox.moe/wpj4iy.mp4",
      "https://files.catbox.moe/sn2kmf.mp4"
    ]
  };

  // 🧠 Xác định đường dẫn đúng
  const segments = event.path.split("/").filter(Boolean);
  const category = segments[segments.length - 1]; // Lấy phần cuối cùng (vd: hentai3d)

  // Nếu chỉ truy cập /api → liệt kê category
  if (category === "api") {
    const result = {};
    for (const [key, value] of Object.entries(data)) {
      result[key] = value.length;
    }
    return {
      statusCode: 200,
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(result, null, 2),
    };
  }

  // Nếu category không tồn tại
  if (!data[category]) {
    return {
      statusCode: 404,
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ error: "category_not_found" }),
    };
  }

  // ✅ Trả random video
  const items = data[category];
  const randomItem = items[Math.floor(Math.random() * items.length)];
  return {
    statusCode: 200,
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      url: randomItem,
      count: items.length,
      category,
    }),
  };
}
